### ISSUE TITLE
libGL.so.1: no such file or directory

### ISSUE THREAD

**Issue by erelsgl** [ai-forever/Kandinsky-2.0#8]
I installed Kandinskiy on an Ubuntu 22.04 machine using WIndows-Subsystem-Linux. When I tried to import it, I got an error:

```
>>> from kandinsky2 import get_kandinsky2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/kandinsky2/__init__.py", line 2, in <module>
    from .kandinsky2_model import Kandinsky2
  File "/usr/local/lib/python3.10/dist-packages/kandinsky2/kandinsky2_model.py", line 4, in <module>
    import cv2
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by erelsgl** [comment]
Based on [this link](https://stackoverflow.com/a/63377623/827927), I did:
```
apt-get install ffmpeg libsm6 libxext6  
```

But I am not sure if this is the correct solution.

**Comment by tikitong** [comment]
@erelsgl 
```
pip install 'git+https://github.com/ai-forever/Kandinsky-2.git'
pip install git+https://github.com/openai/CLIP.git
pip install opencv-python
apt-get install -y libgl1-mesa-dev
```
works for me !
